blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/flutter-form-builder-ecosystem
    about: Please ask and answer questions on Github Discussion of each repository
