name: Build package & run tests

## Caller of this workflow should use it as follows:
## jobs:
##   build:
##     uses: flutter-form-builder-ecosystem/.github/.github/workflows/minimal-quality.yaml@main

on:
  workflow_call:
    inputs:
        codecov-name:
          type: string
          description: 'Name of the codecov report. If empty, unit test will not be run.'
        enable-fix-tests:
          type: boolean
          description: 'Enable run fix tests. By default false'
          default: false
        fvm-flavor:
          type: string
          description: 'Name of fvm flavor. Tipically a channel name. By default: stable'
          default: stable
  
jobs:
  build:
    name: Build package & run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Use shallow clone for faster checkout
      - name: Check broken links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "**/*.md"
      - name: Setup Flutter
        uses: kuhnroyal/flutter-fvm-config-action/setup@v3
        with:
          path: '.fvmrc'
          flavor: ${{ inputs.fvm-flavor }}
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format --set-exit-if-changed lib/ test/ example/
      - name: Analyze static code
        run: flutter analyze
      - name: Run fixes tests
        if: ${{ inputs.enable-fix-tests }}
        run: dart fix --compare-to-golden test_fixes/
      - name: Run unit and widget tests
        if: ${{ inputs.codecov-name != '' }}
        run: flutter test --no-pub --coverage
      - name: Upload coverage to Codecov
        if: ${{ inputs.codecov-name != '' }} && ${{ inputs.fvm-flavor == 'stable' }}
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          name: ${{ inputs.codecov-name }}
      - name: Check publish warnings
        run: dart pub publish --dry-run
